# Generated by Django 3.2.4 on 2024-06-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('measurement', models.CharField(choices=[('milliliter - ml', 'milliliter - ml'), ('deciliter - dl', 'deciliter - dl'), ('litre - l', 'litre - l'), ('teaspoon - tsp', 'teaspoon - tsp'), ('tablespoon - tbsp', 'tablespoon - tbsp'), ('fluid ounce - fl oz', 'fluid ounce - fl oz'), ('cup - c', 'cup - c'), ('pint - pt', 'pint - pt'), ('quart - qt', 'quart - qt'), ('gallon - gal', 'gallon - gal'), ('milligram - mg', 'milligram - mg'), ('gram - g', 'gram - g'), ('kilogram - kg', 'kilogram - kg'), ('pound - lb', 'pound - lb'), ('ounce - oz', 'ounce - oz')], default='gram - g', max_length=50)),
            ],
        ),
    ]
