# Generated by Django 3.2.4 on 2024-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('milliliter - ml', 'milliliter - ml'), ('deciliter - dl', 'deciliter - dl'), ('litre - l', 'litre - l'), ('teaspoon - tsp', 'teaspoon - tsp'), ('tablespoon - tbsp', 'tablespoon - tbsp'), ('fluid ounce - fl oz', 'fluid ounce - fl oz'), ('cup - c', 'cup - c'), ('pint - pt', 'pint - pt'), ('quart - qt', 'quart - qt'), ('gallon - gal', 'gallon - gal'), ('milligram - mg', 'milligram - mg'), ('gram - g', 'gram - g'), ('kilogram - kg', 'kilogram - kg'), ('pound - lb', 'pound - lb'), ('ounce - oz', 'ounce - oz'), ('Elf', 'Elf')], default='gram - g', max_length=50),
        ),
    ]
