# Generated by Django 3.2.4 on 2024-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ingredient_measurement',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ingredient_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ingredient_quantity',
        ),
        migrations.AddField(
            model_name='post',
            name='directions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meals',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('appetizer', 'appetizer'), ('dessert', 'dessert'), ('snack', 'snack')], default='lunch', max_length=50),
        ),
    ]
