# Generated by Django 3.2.4 on 2024-06-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Ingredient'),
        ),
    ]
