# Generated by Django 3.2.4 on 2024-06-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
