<<<<<<< HEAD
# Generated by Django 3.2.4 on 2024-06-17 11:19
=======
# Generated by Django 3.2.4 on 2024-06-17 10:54
>>>>>>> 4b1db6a2734ae9be4f35777ed87d5e40feed4e7f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240605_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
<<<<<<< HEAD
            field=models.ImageField(default='../default_profile_vhiaki', upload_to='images/'),
=======
            field=models.ImageField(default='../default_profile_fkbq0f', upload_to='images/'),
>>>>>>> 4b1db6a2734ae9be4f35777ed87d5e40feed4e7f
        ),
    ]
