# Generated by Django 3.2.4 on 2024-06-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
